### ISSUE TITLE
请问如何正确的启动后端？

### ISSUE THREAD

**Issue by sty945** [adminV/Vue-dataAc-server#1]
您好，请问如何进行正确的后端启动？mongodb数据库的表需要自己新建么？应该如何新建数据库表的？

我先用`npm run dev`启动了`Vue-dataAc-server`后端，再用`npm run serve`启动了这个`Vue-dataAc`的服务，然后将`Vue-dataAc/src/config/config.js`中的postUrl改成了`Vue-dataAc-server`后端启动的地址，但是前端的日志请求还是请求http://data.isjs.cn，请问正确的操作应该是怎么样的？非常感谢

**Comment by adminV** [comment]
1： 此服务需要本地安装MongoDB即可运行
2：Vue-dataAc 中对于上报接口有单独的配置项。如果需要与本地联调，可以参考我的nginx配置:
`	{
	  	listen 80;
		ssl off;
		ssl_certificate /etc/nginx/ssl/1_open.isjs.cn_bundle.crt;
		ssl_certificate_key /etc/nginx/ssl/2_open.isjs.cn.key;
		server_name data.isjs.cn;
		index index.html index.htm index.php default.html default.htm default.php;
		root  /home/GitHub/Vue-dataAc/example/;

    		location /logStash/ {
                	proxy_pass http://127.0.0.1:7007/;
            	}

		location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
			{
				expires      30d;
			}

		location ~ .*\.(js|css)?$
			{
				expires      12h;
			}

		access_log off;
	}`
